key = "AnimationFillModeItem"
value = ["typing = \"Unit\"\nident = \"None\"\nfield = []\n", "typing = \"Unit\"\nident = \"Forwards\"\nfield = []\n", "typing = \"Unit\"\nident = \"Backwards\"\nfield = []\n", "typing = \"Unit\"\nident = \"Both\"\nfield = []\n"]
