key = "BackgroundPositionValue"
value = ["typing = \"Unnamed\"\nident = \"Top\"\nfield = [\"Length\"]\n", "typing = \"Unnamed\"\nident = \"Bottom\"\nfield = [\"Length\"]\n", "typing = \"Unnamed\"\nident = \"Left\"\nfield = [\"Length\"]\n", "typing = \"Unnamed\"\nident = \"Right\"\nfield = [\"Length\"]\n"]
