key = "BackgroundSizeItem"
value = ["typing = \"Unit\"\nident = \"Auto\"\nfield = []\n", "typing = \"Unnamed\"\nident = \"Length\"\nfield = [\"Length\", \"Length\"]\n", "typing = \"Unit\"\nident = \"Cover\"\nfield = []\n", "typing = \"Unit\"\nident = \"Contain\"\nfield = []\n"]
