key = "BackgroundPositionItem"
value = ["typing = \"Unnamed\"\nident = \"Pos\"\nfield = [\"BackgroundPositionValue\", \"BackgroundPositionValue\"]\n", "typing = \"Unnamed\"\nident = \"Value\"\nfield = [\"BackgroundPositionValue\"]\n"]
