key = "BackgroundAttachmentItem"
value = ["typing = \"Unit\"\nident = \"Scroll\"\nfield = []\n", "typing = \"Unit\"\nident = \"Fixed\"\nfield = []\n", "typing = \"Unit\"\nident = \"Local\"\nfield = []\n"]
