key = "Float"
value = ["typing = \"Unit\"\nident = \"None\"\nfield = []\n", "typing = \"Unit\"\nident = \"Left\"\nfield = []\n", "typing = \"Unit\"\nident = \"Right\"\nfield = []\n", "typing = \"Unit\"\nident = \"InlineStart\"\nfield = []\n", "typing = \"Unit\"\nident = \"InlineEnd\"\nfield = []\n"]
