key = "FontDisplay"
value = ["typing = \"Unit\"\nident = \"Auto\"\nfield = []\n", "typing = \"Unit\"\nident = \"Block\"\nfield = []\n", "typing = \"Unit\"\nident = \"Swap\"\nfield = []\n", "typing = \"Unit\"\nident = \"Fallback\"\nfield = []\n", "typing = \"Unit\"\nident = \"Optional\"\nfield = []\n"]
