key = "FontStyle"
value = ["typing = \"Unit\"\nident = \"Normal\"\nfield = []\n", "typing = \"Unit\"\nident = \"Italic\"\nfield = []\n", "typing = \"Unnamed\"\nident = \"Oblique\"\nfield = [\"Angle\"]\n"]
