key = "FontWeight"
value = ["typing = \"Unit\"\nident = \"Normal\"\nfield = []\n", "typing = \"Unit\"\nident = \"Bold\"\nfield = []\n", "typing = \"Unit\"\nident = \"Bolder\"\nfield = []\n", "typing = \"Unit\"\nident = \"Lighter\"\nfield = []\n", "typing = \"Unnamed\"\nident = \"Num\"\nfield = [\"Number\"]\n"]
