key = "Resize"
value = ["typing = \"Unit\"\nident = \"None\"\nfield = []\n", "typing = \"Unit\"\nident = \"Both\"\nfield = []\n", "typing = \"Unit\"\nident = \"Horizontal\"\nfield = []\n", "typing = \"Unit\"\nident = \"Vertical\"\nfield = []\n", "typing = \"Unit\"\nident = \"Block\"\nfield = []\n", "typing = \"Unit\"\nident = \"Inline\"\nfield = []\n"]
