key = "TextDecorationThickness"
value = ["typing = \"Unit\"\nident = \"Auto\"\nfield = []\n", "typing = \"Unit\"\nident = \"FromFont\"\nfield = []\n", "typing = \"Unnamed\"\nident = \"Length\"\nfield = [\"Length\"]\n"]
