key = "TextDecorationStyle"
value = ["typing = \"Unit\"\nident = \"Solid\"\nfield = []\n", "typing = \"Unit\"\nident = \"Double\"\nfield = []\n", "typing = \"Unit\"\nident = \"Dotted\"\nfield = []\n", "typing = \"Unit\"\nident = \"Dashed\"\nfield = []\n", "typing = \"Unit\"\nident = \"Wavy\"\nfield = []\n"]
